# Generated by Django 5.0.4 on 2024-05-26 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_studentprofile_teacherprofile'),
        ('main_quiz', '0014_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_quiz.classroom'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
