# Generated by Django 5.0.4 on 2024-08-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_studentprofile_classroom_studentprofile_user'),
        ('main_quiz', '0016_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='classroom',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='classrooms',
            field=models.ManyToManyField(related_name='students', to='main_quiz.classroom'),
        ),
    ]
