# Generated by Django 4.1.5 on 2023-01-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestable',
            name='average_percentage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='timestable',
            name='times_table',
            field=models.IntegerField(),
        ),
    ]
