# Generated by Django 4.1.5 on 2023-01-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_quiz', '0004_question_times_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_tt', models.IntegerField(default=1)),
                ('one_avg', models.IntegerField(default=0)),
                ('two_tt', models.IntegerField(default=2)),
                ('two_avg', models.IntegerField(default=0)),
                ('three_tt', models.IntegerField(default=3)),
                ('three_avg', models.IntegerField(default=0)),
                ('four_tt', models.IntegerField(default=4)),
                ('four_avg', models.IntegerField(default=0)),
                ('five_tt', models.IntegerField(default=5)),
                ('five_avg', models.IntegerField(default=0)),
                ('six_tt', models.IntegerField(default=6)),
                ('six_avg', models.IntegerField(default=0)),
                ('seven_tt', models.IntegerField(default=7)),
                ('seven_avg', models.IntegerField(default=0)),
                ('eight_tt', models.IntegerField(default=8)),
                ('eight_avg', models.IntegerField(default=0)),
                ('nine_tt', models.IntegerField(default=9)),
                ('nine_avg', models.IntegerField(default=0)),
                ('ten_tt', models.IntegerField(default=10)),
                ('ten_avg', models.IntegerField(default=0)),
            ],
        ),
    ]
