# Generated by Django 4.1.5 on 2023-01-28 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_quiz', '0005_questionoverview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionoverview',
            old_name='eight_tt',
            new_name='eight_times_table',
        ),
        migrations.RenameField(
            model_name='questionoverview',
            old_name='five_tt',
            new_name='five_times_table',
        ),
        migrations.RenameField(
            model_name='questionoverview',
            old_name='four_tt',
            new_name='four_times_table',
        ),
        migrations.RenameField(
            model_name='questionoverview',
            old_name='nine_tt',
            new_name='nine_times_table',
        ),
        migrations.RenameField(
            model_name='questionoverview',
            old_name='one_tt',
            new_name='one_times_table',
        ),
        migrations.RenameField(
            model_name='questionoverview',
            old_name='seven_tt',
            new_name='seven_times_table',
        ),
        migrations.RenameField(
            model_name='questionoverview',
            old_name='six_tt',
            new_name='six_times_table',
        ),
        migrations.RenameField(
            model_name='questionoverview',
            old_name='ten_tt',
            new_name='ten_times_table',
        ),
        migrations.RenameField(
            model_name='questionoverview',
            old_name='three_tt',
            new_name='three_times_table',
        ),
        migrations.RenameField(
            model_name='questionoverview',
            old_name='two_tt',
            new_name='two_times_table',
        ),
    ]
