# Generated by Django 4.1.5 on 2023-01-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_quiz', '0007_questionoverview_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoverview',
            name='eleven_avg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionoverview',
            name='eleven_times_table',
            field=models.IntegerField(default=11),
        ),
        migrations.AddField(
            model_name='questionoverview',
            name='twelve_avg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionoverview',
            name='twelve_times_table',
            field=models.IntegerField(default=12),
        ),
    ]
