# Generated by Django 4.1.5 on 2023-01-29 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_quiz', '0008_questionoverview_eleven_avg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timestable',
            name='average_percentage',
        ),
    ]
