# Generated by Django 4.1.5 on 2023-02-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_quiz', '0009_remove_timestable_average_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoverview',
            name='eight_average_list',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='questionoverview',
            name='eleven_average_list',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='questionoverview',
            name='five_average_list',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='questionoverview',
            name='four_average_list',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='questionoverview',
            name='nine_average_list',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='questionoverview',
            name='one_average_list',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='questionoverview',
            name='seven_average_list',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='questionoverview',
            name='six_average_list',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='questionoverview',
            name='ten_average_list',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='questionoverview',
            name='three_average_list',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='questionoverview',
            name='twelve_average_list',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='questionoverview',
            name='two_average_list',
            field=models.TextField(default='[]'),
        ),
    ]
