# Generated by Django 4.1.5 on 2023-02-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_quiz', '0010_questionoverview_eight_average_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionoverview',
            name='eight_times_table',
            field=models.IntegerField(default=8, editable=False),
        ),
        migrations.AlterField(
            model_name='questionoverview',
            name='eleven_times_table',
            field=models.IntegerField(default=11, editable=False),
        ),
        migrations.AlterField(
            model_name='questionoverview',
            name='five_times_table',
            field=models.IntegerField(default=5, editable=False),
        ),
        migrations.AlterField(
            model_name='questionoverview',
            name='four_times_table',
            field=models.IntegerField(default=4, editable=False),
        ),
        migrations.AlterField(
            model_name='questionoverview',
            name='nine_times_table',
            field=models.IntegerField(default=9, editable=False),
        ),
        migrations.AlterField(
            model_name='questionoverview',
            name='one_times_table',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='questionoverview',
            name='seven_times_table',
            field=models.IntegerField(default=7, editable=False),
        ),
        migrations.AlterField(
            model_name='questionoverview',
            name='six_times_table',
            field=models.IntegerField(default=6, editable=False),
        ),
        migrations.AlterField(
            model_name='questionoverview',
            name='ten_times_table',
            field=models.IntegerField(default=10, editable=False),
        ),
        migrations.AlterField(
            model_name='questionoverview',
            name='three_times_table',
            field=models.IntegerField(default=3, editable=False),
        ),
        migrations.AlterField(
            model_name='questionoverview',
            name='twelve_times_table',
            field=models.IntegerField(default=12, editable=False),
        ),
        migrations.AlterField(
            model_name='questionoverview',
            name='two_times_table',
            field=models.IntegerField(default=2, editable=False),
        ),
    ]
