# Generated by Django 4.1.5 on 2023-02-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_quiz', '0011_alter_questionoverview_eight_times_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionoverview',
            name='eight_times_table',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='questionoverview',
            name='eleven_times_table',
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='questionoverview',
            name='five_times_table',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='questionoverview',
            name='four_times_table',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='questionoverview',
            name='nine_times_table',
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='questionoverview',
            name='one_times_table',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='questionoverview',
            name='seven_times_table',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='questionoverview',
            name='six_times_table',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='questionoverview',
            name='ten_times_table',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='questionoverview',
            name='three_times_table',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='questionoverview',
            name='twelve_times_table',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='questionoverview',
            name='two_average_list',
            field=models.TextField(default='[]', editable=False),
        ),
        migrations.AlterField(
            model_name='questionoverview',
            name='two_times_table',
            field=models.IntegerField(default=2),
        ),
    ]
