# Generated by Django 5.0.4 on 2024-05-28 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_quiz', '0014_classroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_4',
        ),
        migrations.AlterField(
            model_name='question',
            name='times_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_quiz.timestable'),
        ),
        migrations.DeleteModel(
            name='QuestionOverview',
        ),
    ]
